# Generated by Django 4.2.4 on 2023-10-04 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atend', models.CharField(max_length=120)),
                ('telefone_atend', models.CharField(max_length=24)),
                ('observacao_atend', models.TextField()),
                ('criado_em_atend', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em_atend', models.DateTimeField(auto_now_add=True)),
                ('ativo_atend', models.BooleanField()),
                ('user_atend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('encerrado', models.BooleanField()),
                ('atendente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App_SAC.atendente')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('telefone', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=120)),
                ('observacao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_departamento', models.CharField(max_length=30)),
                ('info_departamento', models.TextField(null=True)),
                ('ativo_departamento', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Situacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_situacao', models.CharField(max_length=30)),
                ('info_situacao', models.TextField(null=True)),
                ('ativo_situacao', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Situacao_Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_hora', models.DateTimeField()),
                ('id_atendimento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='atendimentos', to='App_SAC.atendimento', verbose_name='Atendimento')),
                ('id_situacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='situacoes', to='App_SAC.situacao', verbose_name='Situacao')),
            ],
        ),
        migrations.AddField(
            model_name='atendimento',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App_SAC.cliente'),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='App_SAC.departamento'),
        ),
    ]
